### ISSUE TITLE
Turn off auto updates

### ISSUE THREAD

**Issue by paulwsully** [smasherprog/EqTool#72] opened 2023-12-13 23:28 UTC
Any chance you can add a toggle to turn off auto updates? Or to just update on startup? Super frustrating sometimes being in the middle of something, only to have spell timers completely vanish.

**Comment by casey-mccarthy** [comment] 2023-12-14 19:13
I came to add a request to preserve mob timers after the auto update occurs. Found this issue. Think this is a valuable feature to at least keep timers running across updates or restarts of the client.

**Comment by smasherprog** [comment] 2023-12-15 15:28
yeah its only an issue when you loose the state of things. Ill be working to make sure everything is saved through an update. This should fix the problem.

**Comment by paulwsully** [comment] 2023-12-29 01:17
> yeah its only an issue when you loose the state of things. Ill be working to make sure everything is saved through an update. This should fix the problem.

Any progress on this? It's getting pretty frustrating constantly seeing the update screen, even despite it having already updated, only to have it move my windows around again.

**Comment by Anthony-Harvey** [comment] 2024-01-05 00:21
> its only an issue when you loose the state of things

Also an issue when you remove features like Always on Top toggle.

**Comment by smasherprog** [comment] 2024-01-06 18:11
Added code to make check for updates less aggressive. Will only do updates if there are less than 2 items total in the entire triggers window.
This will be doing out today

**Comment by smasherprog** [comment] 2024-01-06 18:38
Update released. Gonna close this ticket now.

**Closed by smasherprog** 2024-01-06 18:38 UTC

**Comment by paulwsully** [comment] 2024-01-09 15:27
So, this is better for not interrupting the user while they are actively casting something, but I'd really like to see just a button to check for updates. I'd prefer to be fully in control of when software I use updates. It's also just generally mildly annoying having to close the update window every single time I open the tool. Especially when it's mostly features I simply won't or rarely use.

Thanks for the work you're doing on this. It's a great tool and really enjoying using it overall!

**Comment by smasherprog** [comment] 2024-01-09 16:13
The fix I am going to implement for this is NOT to give people an option to turn off updates. 
The fix will be to save state between updates and then turn back on the 'self update when ever one is available'
Since that seems to be the issue is the LOST information. A few seconds where the program updates is annoying, but if i give the option to not update, no one will ever get updates.

**Comment by paulwsully** [comment] 2024-01-15 01:06
> The fix I am going to implement for this is NOT to give people an option to turn off updates. The fix will be to save state between updates and then turn back on the 'self update when ever one is available' Since that seems to be the issue is the LOST information. A few seconds where the program updates is annoying, but if i give the option to not update, no one will ever get updates.

Forcing updates on people is super frowned upon for any software. You're taking away your users agency over their own computers by forcing them. Not to mention I constantly see the same update window popup multiple times, despite dismissing it. It also resets my window positions every single time it happens.

I also have lost track of the number of times I've gotten the update window while in the middle of a dungeon and actively using my map, only to have to stop and wait to be able to use a map again.

I really hope you reconsider your stance on how you handle updates and switch to how most other software developers handle it.

Thanks

**Comment by smasherprog** [comment] 2024-01-15 07:27
I am always improving the program. I have a to do list and making updates easier on users is on there. So, it will get better at some point!

**Comment by paulwsully** [comment] 2024-01-15 15:01
> I am always improving the program. I have a to do list and making updates easier on users is on there. So, it will get better at some point!

Glad to hear it. Looking forward to being able to use EQTool again at that point!
